# Generated by Django 4.2 on 2023-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenismentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=30)),
                ('organization_legal_address', models.CharField(max_length=90)),
                ('organization_inn', models.CharField(max_length=12)),
                ('organization_kpp', models.CharField(max_length=9)),
                ('contract_number', models.CharField(max_length=12)),
                ('contract_date', models.DateTimeField(auto_now_add=True)),
                ('payment_sum_without_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_payment_sum', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
